base_url = "https://filipcorlan.com"
title = "Filip Corlan"
description = "Homepage"
author = "Filip Corlan"
default_language = "en"
theme = "lagrange"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", render = false },
  { name = "categories", render = false },
]

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[markdown.highlighting]
style = "inline"
theme = "github-light"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
menu = [
  { name = "Projects", url = "/projects" },
]
social = [
  { name = "GitHub", icon = "github", url = "https://github.com/filipcrl" },
  { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/filipcorlan" },
]
posts_section = "projects/_index.md"
homepage_title = "Filip Corlan's Homepage"
header_bio = "Master's student in Electrical Engineering at EPFL. Interested in FPGA, PCB and chip design, networking, functional programming, and compilers."
older_page = "Older"
newer_page = "Newer"
read_more = "Read more"
post_date_prefix = "Written on"
sharing_button_prompt = "Feel free to share!"
related_posts = "You may also enjoy:"
hide_post_date = false
hide_post_share = true
hide_related_posts = true
disqus_shortname = ""
google_analytics_id = ""
